version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    restart: always
    volumes:
      - .:/app
    ports:
      - 80:8000
    environment:
      - POSTGRES_URL_DOCKER=postgresql://yandex:A8lOApWmNGigLuKu@db:5432/yandex_shbr
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=yandex
      - POSTGRES_PASSWORD=A8lOApWmNGigLuKu
      - POSTGRES_DB=yandex_shbr

volumes:
  postgres_data: